### ISSUE TITLE
deviseのセットアップを行う。

### ISSUE THREAD

**Issue by katsuya-yamaguchi** [katsuya-yamaguchi/practice-ruby#3]
## TODO
- [x] rails devise:installを実施する。
- [x] rails devise:viewsを実施する。（devise用のViewを作成）
- [x] rails g controller Home index showを実施する。（コントローラーを作成）
- [x] rails g devise Userを実施する。（devise用のモデルを作成）
- [x] DBマイグレートを実施する。
